language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - yarn
  - yarn build && yarn start
  - yarn export
  - touch out
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    branch: main
